### ISSUE TITLE
File name too long when building pyhessio

### ISSUE THREAD

**Issue by orelgueta** [cta-observatory/training-material#6]
Hi,
I get an error that the file name is too long when I try to build pyhessio (see below). Not sure where all the place holders come from.
Thanks for your help.

```
$ conda build pyhessio
BUILD START: pyhessio-0.5.7-py3
updating index in: /home/orel/work/software/anaconda3/conda-bld/linux-64
updating index in: /home/orel/work/software/anaconda3/conda-bld/noarch

The following NEW packages will be INSTALLED:

    mkl:        11.3.3-0      (soft-link)
    numpy:      1.11.2-py35_0 (soft-link)
    openssl:    1.0.2j-0      (soft-link)
    pip:        8.1.2-py35_0  (soft-link)
    python:     3.5.2-0       (soft-link)
    readline:   6.2-2         (soft-link)
    setuptools: 27.2.0-py35_0 (soft-link)
    sqlite:     3.13.0-0      (soft-link)
    tk:         8.5.18-0      (soft-link)
    wheel:      0.29.0-py35_0 (soft-link)
    xz:         5.2.2-0       (soft-link)
    zlib:       1.2.8-3       (soft-link)

Traceback (most recent call last):
  File "/home/orel/work/software/anaconda3/lib/python3.5/site-packages/conda/history.py", line 86, in update
    self.init_log_file()
  File "/home/orel/work/software/anaconda3/lib/python3.5/site-packages/conda/history.py", line 76, in init_log_file
    self.write_dists(linked(self.prefix))
  File "/home/orel/work/software/anaconda3/lib/python3.5/site-packages/conda/history.py", line 250, in write_dists
    os.makedirs(self.meta_dir)
  File "/home/orel/work/software/anaconda3/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/orel/work/software/anaconda3/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '/home/orel/work/software/anaconda3/conda-bld/pyhessio_1476025439175/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/orel/work/software/anaconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/orel/work/software/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 246, in main
    execute(sys.argv[1:])
  File "/home/orel/work/software/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 238, in execute
    already_built=None, config=config)
  File "/home/orel/work/software/anaconda3/lib/python3.5/site-packages/conda_build/api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "/home/orel/work/software/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 1004, in build_tree
    config=recipe_config)
  File "/home/orel/work/software/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 561, in build
    create_env(config.build_prefix, specs, config=config)
  File "/home/orel/work/software/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 431, in create_env
    plan.execute_actions(actions, index, verbose=config.debug)
  File "/home/orel/work/software/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 642, in execute_actions
    with History(actions[inst.PREFIX]):
  File "/home/orel/work/software/anaconda3/lib/python3.5/site-packages/conda/history.py", line 67, in __enter__
    self.update('enter')
  File "/home/orel/work/software/anaconda3/lib/python3.5/site-packages/conda/history.py", line 105, in update
    raise CondaFileIOError(self.path, "Can't write the history file %s" % e)
conda.exceptions.CondaFileIOError: IO error: Couldn't read or write to file. '/home/orel/work/software/anaconda3/conda-bld/pyhessio_1476025439175/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/conda-meta/history'. Can't write the history file [Errno 36] File name too long: '/home/orel/work/software/anaconda3/conda-bld/pyhessio_1476025439175/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_'
```

**Comment by jacquemier** [comment]
pyhessio can be also compiled and installed with python setuptool.
Could you please try this:

prompt$ > python setup.py build
prompt$ > python setup.py install 

Are you  present in Paris for ctapipe bootcamp ?

**Comment by orelgueta** [comment]
This seems to work, thanks!
I am at the bootcamp, yes, sitting in the back with a black shirt.
